### PR TITLE
CSS Solution for fixing the carret by the mobile description

### LINKED ISSUE #504: Snippet preview: mobile description "arrow" is not visible
Compare with the desktop snippet preview: hover or click the description and the "arrow" appears on the left:

screen shot 2018-05-07 at 12 56 44

Instead, in the mobile snippet preview, the arrow is not visible:

screen shot 2018-05-07 at 12 56 53

See `overflow: hidden` used on the `MobileDescription`, which prevents the arrow to be visible.

### PR DESCRIPTION
**Pull request by Xyfi**
## Summary

This PR can be summarized in the following changelog entry:

* Fixes arrow not showing up next to mobile description on hover and selection.

## Relevant technical choices:

*

## Test instructions

This PR can be tested by following these steps:

*

Fixes #504

### CODE REVIEW

File: composites/Plugin/SnippetPreview/components/SnippetPreview.js [hunk 1]
```diff
@@ -542,6 +546,53 @@ export default class SnippetPreview extends PureComponent {
...
+				<DesktopDescriptionWithCarret { ...outerContainerProps }
+											  innerRef={ this.setDescriptionRef }>
+					{ renderedDate }
+					{ highlightKeyword( locale, keyword, this.getDescription() ) }
+				</DesktopDescriptionWithCarret>
+			);
+		} else if ( mode === MODE_MOBILE ) {
+			const MobileDescriptionWithCarret = this.addCaretStyles( "description", MobileDescription );
+			return (
+				<MobileDescriptionWithCarret
```
Comment (boblinthorst) [inline composites/Plugin/SnippetPreview/components/SnippetPreview.js]: caret*

**Comment by boblinthorst** [comment]
CR and Acceptance :+1:
